name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: lts/fermium
    - run: npm i
    - run: nohup node server.js 2>&1 > server.log &
    - run: npm i -g speed-test && speed-test -vb
    - run: cat server.log
    - uses: actions/upload-artifact@v2
      with:
       name: server-log
       path: server.log
